import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
   <div className={styles.container}>
      <Head>
        <title>The Holy Bible</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
     
      <main className={styles.main}>
    
       <h2 className={styles.holy}>The Holy</h2>
                <h1 className={styles.title}>
                    <a href="https://en.wikipedia.org/wiki/Bible">Bible</a>
                </h1>
                          <div className={styles.hero}>
                             <Image 
                                src="/gods-finger.jpg"
                                alt="Picture of the Gods finger"
                                height={900}
                                width={2000}
                                priority
                              />
                              <p className={styles.transcribed}>
                                Transcribed by: Jason Daniel Nutt
                              </p>
                          </div>
                        <ul className={styles.index}>
                        <a href="https://waggin-rights.vercel.app/">  
                          <li className={styles.li}>The gospel of Matthew</li>  
                        </a>
                      
                           <li className={styles.li}>The gospel of Mark</li>  
                            <li className={styles.li}>The gospel of Luke</li>  
                           <li className={styles.li}>The gospel of John</li>  
                           <li className={styles.li}>Acts</li> 

                            <li className={styles.li}>Romans</li>  
                           <li className={styles.li}>1 Corinthians</li>  
                            <li className={styles.li}>2 Corinthians</li>  
                           <li className={styles.li}>Ephesians</li>  
                           <li className={styles.li}>Philippians</li>  


                               <li className={styles.li}>1 Thessalonians</li>  
                           <li className={styles.li}>2 Thessalonians</li>  
                            <li className={styles.li}>James</li>  
                           <li className={styles.li}>Jude</li>  
                           <li className={styles.li}>1 Peter</li>  
                        </ul>

                    
    
      </main>

    </div>
  )
}
