import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Holy Bible</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Holy  <a href="https://en.wikipedia.org/wiki/Bible">Bible</a>
        </h1>
        <h2 className={styles.h2}>The New Covenant: a binding agreement</h2>
        <p className={styles.description}> 
        <code className={styles.publisher}>
          Coded, Published & Deployed by: Jason Daniel Nutt.
        </code>
        </p>
        <p className={styles.description}> 
        <code className={styles.publisher}>
          Illustrations borrowed from the Bible Project
        </code>
        </p>


        <a href="https://bibleproject.com/downloads/posters/#load-posters-311">
        <Image className={styles.illustration}
          src="/NT_Overview.jpeg"
          alt="new testament illustration"
          layout="intrinsic"
          height="900px"
          width="1600px"
        />
       </a>
        <p className={styles.description}>
        <code className={styles.code}>Then a cloud appeared and covered them. And a voice came from the cloud. THIS IS MY SON, WHOM I LOVE, LISTEN TO HIM. </code>
        </p>
      
        <div className={styles.grid}>
        <a href="https://bibleproject.com/downloads/posters/#load-posters-250">
        <Image className={styles.card1}
          src="/44-Mark.jpeg"
          alt="new testament illustration"
          layout="intrinsic"
          height="300px"
          width="300px"
        />
        </a>
          <a href="https://mark-alpha.vercel.app/" className={styles.card}>
            <h2>Mark &darr;</h2>
            <p>The book of Mark, which stresses facts & actions, rather than themes or topics, is the most exciting account of the life of Christ among the Gospels. </p>
          </a>
          <a href="https://bibleproject.com/downloads/posters/#load-posters-249">
          <Image className={styles.card1}
          src="/42-Matthew-FNL-1.jpeg"
          alt="new testament illustration"
          layout="intrinsic"
          height="300px"
          width="300px"
        />
        </a>
          <a href="https://matthew-coral.vercel.app/" className={styles.card}>
            <h2>Matthew &darr;</h2>
            <p>Matthew is the most Jewish-centric of the four gospels. The apostle regularly invoked the writings of the Old Testament prophets...</p>
          </a>
          <a href="https://bibleproject.com/downloads/posters/#load-posters-251">
          <Image className={styles.card1}
          src="/45-john.jpeg"
          alt="new testament illustration"
          layout="intrinsic"
          height="300px"
          width="300px"
        />
        </a>
          <a
            href="https://john-zeta.vercel.app/"
            className={styles.card}
          >
            <h2>John &darr;</h2>
            <p>An eyewitness account of Jesus ministry, enriched by the authors understanding of Jewish traditions & knowledge of Palestine.</p>
          </a>
        
          <a href="https://bibleproject.com/downloads/posters#load-posters-252"> 
          <Image className={styles.card1}
          src="/48-Luke-FNL.jpeg"
          alt="new testament illustration"
          layout="intrinsic"
          height="300px"
          width="300px"
        />
        </a>
          <a
            href="https://luke-three.vercel.app/"
            className={styles.card}
          >
            <h2>Luke &darr;</h2>
            <p>
            Lukes account of Jesus ministry divides into 3 parts:
            events that occurred in & around Galilee, 
             in Judea & Perea
            & his final week in Jerusalem 
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
